Repository codeready-toolchain/registration-service, pull requests merged in 2019-12, with the labels that each got.

#75 chore(CRT-361): move SA and namespace name definition into deployment template
  deploy/registration-service.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  make/build.mk
  make/dev.mk
  make/generate.mk
Labels: approved, size/L

#77 Added leeway support for IssuedAt claim to allow for time skew issues
  pkg/auth/tokenparser.go
Labels: approved, size/S

#76 Remove deprecated TargetCluster from MUR status
  go.mod
  go.sum
Labels: approved, size/M

#79 updating to using latest common
  go.mod
  go.sum
  pkg/auth/tokenparser_test.go
  pkg/middleware/middleware_test.go
Labels: approved, size/M

#80 chore: move functions for (un)setting env variables to common
  go.mod
  go.sum
  pkg/auth/keymanager_test.go
  pkg/configuration/configuration_test.go
  test/unset_env_var_and_restore.go
  test/unset_env_var_and_restore_test.go
Labels: approved, size/L

#82 adding usersignup annotation for email
  go.mod
  go.sum
  pkg/controller/signup.go
  pkg/controller/signup_test.go
  pkg/signup/signup_service.go
  pkg/signup/signup_service_test.go
Labels: approved, size/M

#83 Add Che Dashboard URL to GET /v1/signup response
  go.mod
  go.sum
  pkg/controller/signup_test.go
  pkg/signup/signup_service.go
  pkg/signup/signup_service_test.go
Labels: approved, size/S

#84 Add Che Dashboard URL to landing page
  pkg/assets/index.html
  pkg/assets/landingpage.js
Labels: approved, size/XS

#85 removing showError
  pkg/assets/landingpage.js
Labels: approved, size/XS

#86 Check all 2xx httpstatus
  pkg/assets/landingpage.js
Labels: approved, size/XS
