Repository codeready-toolchain/registration-service, pull requests merged in 2019-11, with the labels that each got.

#61 Registration service e2e tests
  go.mod
  go.sum
  pkg/auth/keymanager_test.go
  pkg/auth/tokenparser_test.go
  pkg/middleware/middleware_test.go
  test/tokenmanager.go
  test/tokenmanager_test.go
Labels: approved, size/XL

#65 Switch to go 1.13
  openshift-ci/Dockerfile.tools
Labels: approved, size/S

#66 Add gcc to Dokerfile.tools
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#64 Use OpenShift template to deploy reg-service
  README.adoc
  deploy/deployment.yaml
  deploy/deployment_dev.yaml
  example-config.yml
  make/dev.mk
  make/test.mk
  pkg/auth/keymanager_test.go
  pkg/auth/tokenparser_test.go
  pkg/configuration/configuration.go
  pkg/configuration/configuration_test.go
  pkg/controller/health_check.go
  pkg/controller/health_check_test.go
  pkg/middleware/middleware_test.go
  test/testsuite.go
Labels: approved, size/L

#69 Use UserID as UserSignup.Name
  go.mod
  go.sum
  pkg/controller/signup_test.go
  pkg/signup/signup_service.go
  pkg/signup/signup_service_test.go
Labels: approved, size/L

#70 Makefile target to deploy e2e resources
  README.adoc
  make/dev.mk
  make/test.mk
Labels: approved, size/S

#72 Move username transformation to host operator
  go.mod
  go.sum
  pkg/controller/signup_test.go
  pkg/signup/signup_service.go
  pkg/signup/signup_service_test.go
Labels: approved, size/L

#63 E2e registration service
  pkg/auth/defaultmanager.go
  pkg/auth/keymanager.go
  pkg/auth/keymanager_test.go
  pkg/configuration/configuration_test.go
  test/unset_env_var_and_restore.go
  test/unset_env_var_and_restore_test.go
Labels: approved, size/L

#71 Return Web Console URL in GET /signup
  pkg/assets/index.html
  pkg/controller/signup_test.go
  pkg/signup/signup_service.go
  pkg/signup/signup_service_test.go
Labels: approved, size/L

#73 Landing Page in Pure HTML/CSS
  cmd/main.go
  pkg/assets/codereadyws-logo.svg
  pkg/assets/index.html
  pkg/assets/landingpage.css
  pkg/assets/landingpage.js
  pkg/assets/openshift-logo.svg
  pkg/assets/redhat-logo.svg
  pkg/assets/rhdeveloper-logo.svg
  pkg/log/log.go
Labels: approved, lgtm, size/XL
