Repository codeready-toolchain/registration-service, pull requests merged in 2019-10, with the labels that each got.

#55 Cleanup signup handler
  make/depend.mk
  make/generate.mk
  pkg/controller/signup.go
  pkg/controller/signup_test.go
Labels: approved, size/S

#58 Fix transformUserName()
  deploy/deployment_dev.yaml
  deploy/role.yaml
  pkg/configuration/configuration.go
  pkg/kubeclient/signup.go
  pkg/signup/signup_service.go
  pkg/signup/signup_service_test.go
Labels: approved, size/M

#57 deploy in dev with TLS enabled
  deploy/deployment_dev.yaml
Labels: approved, size/XS
