Repository codeready-toolchain/registration-service, pull requests merged in 2020-01, with the labels that each got.

#87 Do not auto-signup if user didn't click on Get Started
  pkg/assets/index.html
  pkg/assets/landingpage.js
Labels: approved, size/S

#88 chore: install github.com/kislyuk/yq binary
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#89 chore(CRT-362): add travis job generating new version of host-operator CSV
  .travis.yml
  make/dev.mk
  make/docker.mk
  make/image.mk
Labels: approved, size/L
