Repository codeready-toolchain/registration-service, pull requests merged in 2020-03, with the labels that each got.

#94 chore: add get/list bannedusers to reg-service SA
  deploy/registration-service.yaml
Labels: approved, size/XS

#92 Check if user has been banned before allowing signup
  pkg/kubeclient/banneduser.go
  pkg/kubeclient/client.go
  pkg/kubeclient/client_test.go
  pkg/signup/signup_service.go
  pkg/signup/signup_service_test.go
  test/fake/banneduser_client.go
Labels: approved, size/L

#95 Fix typo: "Sprint Boot" -> "Spring Boot"
  pkg/assets/index.html
Labels: approved

#97 Update operator-sdk
  .travis.yml
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
Labels: approved
