Repository codeready-toolchain/registration-service, pull requests merged in 2023-10, with the labels that each got.

#348 feat: Implement public API that will open SpaceBindings to end users through proxy part 1
  deploy/README.md
  deploy/registration-service.yaml
  go.mod
  go.sum
  pkg/application/service/services.go
  pkg/informers/informers.go
  pkg/informers/service/informer_service.go
  pkg/kubeclient/resources/names.go
  pkg/proxy/handlers/spacelister.go
  pkg/proxy/handlers/spacelister_test.go
  pkg/proxy/proxy.go
  test/fake/informer.go
Labels: approved

#353 ci: bump actions to silence node12 warnings
  .github/workflows/ci-build.yml
  .github/workflows/ci-check-gomod.yml
  .github/workflows/operator-cd.yml
  .github/workflows/publish-operators-for-e2e-tests.yml
Labels: approved, lgtm, ok-to-test

#354 Fix pending approval error
  pkg/signup/service/signup_service.go
  pkg/signup/service/signup_service_test.go
Labels: approved, ok-to-test

#350 feat: Implement public API that will open SpaceBindings to end users through proxy part 2
  go.mod
  go.sum
  pkg/proxy/handlers/spacelister.go
  pkg/proxy/handlers/spacelister_test.go
  test/fake/informer.go
Labels: approved

#358 fix: binding request field should not be returned when empty
  go.mod
  go.sum
  pkg/proxy/handlers/spacelister.go
  pkg/proxy/handlers/spacelister_test.go
Labels: approved

#357 Change threshold to 1% in codecov settings.
  .codecov.yml
Labels: approved, lgtm

#360 add CODEOWNERS file
  CODEOWNERS
Labels: approved

#355 feat: create usernames response type
  pkg/username/usernames.go
Labels: approved

#362 update grpc version
  go.mod
  go.sum
Labels: approved, lgtm

#352 move proxy metrics to a separate server
  build/Dockerfile
  cmd/main.go
  deploy/registration-service.yaml
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/proxy/handlers/metrics.go
  pkg/proxy/handlers/metrics_test.go
  pkg/proxy/handlers/spacelister.go
  pkg/proxy/handlers/spacelister_test.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
Labels: approved

#363 rename metrics service label
  deploy/registration-service.yaml
Labels: approved

#361 feat: add usernames endpoint in reg-service
  pkg/controller/usernames.go
  pkg/controller/usernames_test.go
  pkg/proxy/handlers/spacelister_test.go
  pkg/server/routes.go
  test/fake/informer.go
Labels: approved

#359 Update UserSignup.Spec.IdentityClaims if missing or different to the user's token
  pkg/signup/service/signup_service.go
  pkg/signup/service/signup_service_test.go
Labels: approved

#364 disable HTTP/2 on all 3 servers
  pkg/metrics/metrics.go
  pkg/proxy/proxy.go
  pkg/server/server.go
Labels: approved

#365 get pr branch name from CLONEREFS_OPTIONS
  make/test.mk
Labels: approved

#366 fix: proxy first request slowness issue
  cmd/main.go
  go.mod
  go.sum
  pkg/proxy/proxy.go
Labels: approved, lgtm
